# Generated by Django 5.1.7 on 2025-03-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attachment', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chats')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chats',
            index=models.Index(fields=['user1', 'user2'], name='chat_chats_user1_i_6acc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='chats',
            index=models.Index(fields=['created_at'], name='chat_chats_created_964863_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chats',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='contents',
            index=models.Index(fields=['chat', 'created_at'], name='chat_conten_chat_id_af858d_idx'),
        ),
        migrations.AddIndex(
            model_name='contents',
            index=models.Index(fields=['sender'], name='chat_conten_sender__1ae198_idx'),
        ),
    ]
